USE [master]
GO

/****** Object:  Database [BRANEF]    Script Date: 21/09/2024 13:20:58 ******/
CREATE DATABASE [BRANEF]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BRANEF', FILENAME = N'D:\Temp\BRANEFDB\BRANEF.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BRANEF_log', FILENAME = N'D:\Temp\BRANEFDB\BRANEF_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BRANEF].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BRANEF] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BRANEF] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BRANEF] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BRANEF] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BRANEF] SET ARITHABORT OFF 
GO

ALTER DATABASE [BRANEF] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BRANEF] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BRANEF] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BRANEF] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BRANEF] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BRANEF] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BRANEF] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BRANEF] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BRANEF] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BRANEF] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BRANEF] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BRANEF] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BRANEF] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BRANEF] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BRANEF] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BRANEF] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BRANEF] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BRANEF] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BRANEF] SET  MULTI_USER 
GO

ALTER DATABASE [BRANEF] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BRANEF] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BRANEF] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BRANEF] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BRANEF] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BRANEF] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BRANEF] SET QUERY_STORE = ON
GO

ALTER DATABASE [BRANEF] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [BRANEF] SET  READ_WRITE 
GO

--------------------------------- 

USE [BRANEF]
GO

/****** Object:  Table [dbo].[EmpresaPorte]    Script Date: 21/09/2024 13:30:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EmpresaPorte](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Descricao] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_EmpresaPortes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

--------------------------------- 

USE [BRANEF]
GO

/****** Object:  Table [dbo].[Cliente]    Script Date: 21/09/2024 13:29:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Cliente](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [nvarchar](250) NOT NULL,
	[EmpresaPorteId] [int] NOT NULL,
 CONSTRAINT [PK_Clientes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Cliente] UNIQUE NONCLUSTERED 
(
	[Nome] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Cliente]  WITH CHECK ADD  CONSTRAINT [FK_Cliente_EmpresaPorte] FOREIGN KEY([EmpresaPorteId])
REFERENCES [dbo].[EmpresaPorte] ([Id])
GO

ALTER TABLE [dbo].[Cliente] CHECK CONSTRAINT [FK_Cliente_EmpresaPorte]
GO

-----------------------------------------

USE [BRANEF]
GO

INSERT INTO [dbo].[EmpresaPorte] ([Descricao])
     VALUES
           ('Pequena'),
		   ('Média'),
		   ('Grande')
GO


